spring.application.name=assets-manager-linebot

# LINE Bot 自身的埠號
server.port=8088

# 核心變更：動態取得雲端儲存服務的 API 網址
# 如果有系統環境變載入，就用環境變數；若無（例如你在本機 IDE 直接按 Run），則自動降級回 localhost
cloud.storage.api-url=${CLOUD_STORAGE_API_URL:http://localhost:8090}

line.bot.handler.enabled=true